config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get 'sessions/new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete "logout" => "sessions#destroy"


  resources :users, constraints: { id: /\d+/ } do
    member do
      get :reset_password, action: "edit_password"
      post :reset_password, action: "update_password"
      post :app, action: "upload_app"
      get :app, action: "download_app"
      get :assets_bundle
      get :videos
    end

    resources :attachments, constraints: { id: /\d+/ } do
      member do
        post "relate_video/:video_id", action: "relate_video", as: "relate_video_attachment"
      end
    end
  end

  resources :clients, constraints: { id: /\d+/ }

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :users, only: [:index, :create, :show, :update, :destroy] do
        member do
          get :images
          get :ar_images
        end
      end
      # 原文有 microposts, 我们现在把它注释掉
      # resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :update_profile

  mount_uploader :gravatar, GravatarUploader
  mount_uploader :app, AppUploader

  has_many :attachments, dependent: :destroy

  # 用户级别，管理员， 操作员， 普通用户
  enum role: [:admin, :operator, :client]

  before_create :generate_authentication_token
  before_save { self.password_text = self.password if self.password.present? }
  # before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_TELEPHONE_REGEX = /\A\d{11}\z/i

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }, unless: Proc.new{|user| user.update_profile == true}

  # validates :email,
  #           length: { maximum: 255},
  #           format: { with: VALID_EMAIL_REGEX},
  #           uniqueness: {case_sensitive: false}, if: Proc.new{|user| user.email.present?}
  # validates :telephone,
  #           presence: true,
  #           format: {with: VALID_TELEPHONE_REGEX},
  #           uniqueness: true


  # 管理员
  scope :admins, ->{where(role: "root")}

  # 操作员
  scope :operators, ->{where(role: "operator")}

  # 普通用户
  scope :clients, ->{where(role: "client")}

  # 返回指定字符串的哈希摘要
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 生成用于API认证的token
  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.base64(64)
      break if !User.find_by(authentication_token: authentication_token)
    end
  end

  def reset_auth_token!
    generate_authentication_token
    save
  end

  def images
    attachments.where(content_type:"jpeg")
  end

  def videos
    attachments.where(content_type:"mp4")
  end

  def targets_json
    h = {}
    h["images"] = []
    self.images.each_with_index do |image, index|
      h["images"] << {"image" => "#{index}.jpg", "name" => "#{index}", "uid" => "#{index}"} if image.video_id.present?
    end

    h
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :authenticate_user!, only: [:show, :update, :images, :ar_images]

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(update_params)
  end

  def images
    @images = current_user.images
  end

  def ar_images
    @images = current_user.images.select{|i| i.has_video?}
  end

  private

  def update_params
    params.require(:user).permit(:name, :telephone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  skip_before_action :check_login, only: [:new, :create, :download_app]

  def index
    if current_user.admin?
      users = User.all
    else
      users = User.clients
    end
    @users = filter_users(users).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(role: "client")
  end

  def create
    set_password_for_client if params[:build_client].present?
    @user = User.new(user_params)
    @user.role = "client"
    if @user.save
      if params[:build_client].present?
        flash[:success] = "创建客户#{@user.name}成功"
      else
        log_in @user
        flash[:success] = "欢迎登陆魔扫应用!"
      end

      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    attrs = {name: params[:user][:name],
             email: params[:user][:email],
             telephone: params[:user][:telephone],
             gravatar: params[:user][:gravatar],
             update_profile: true}
    attrs[:role] = params[:user][:role] if current_user.admin?

    if @user.update(attrs)
      flash[:success] = "用户#{@user.name}信息已成功更新！"
      redirect_to user_path(@user)
    else
      flash.now[:error] = "用户#{@user.name}信息已更新失败！"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:success] = "用户#{@user.name}已成功删除"
    else
      flash[:error] = "用户#{@user.name}删除失败！"
    end

    if current_user.admin?
      redirect_to users_path
    else
      redirect_to clients_path
    end

    #redirect_back fallback_location: users_path
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(params[:id])
    if @user && @user.authenticate(params[:old_password])
      @user.password = params[:password]
      @user.password_confirmation = params[:password_confirmation]

      if @user.save
        flash[:success] = "更新 #{@user.name} 密码成功！"
        redirect_to users_path
        return
      else
        flash.now[:error] = "更新 #{@user.name} 密码失败！"
        render "edit_password"
      end
    else
      flash.now[:error] = "旧的密码输入错误！"
      render "edit_password"
    end
  end

  def upload_app
    @user = User.find(params[:id])

    if @user.update_attribute(:app, params[:app])
      render json: @user.to_json, status: 200
    else
      render json: @user.errors, status: 300
    end
  end

  def download_app
    @user = User.find(params[:id])


    if @user.nil? || @user.app.blank?
      render  "errors/404", status: 404
    else
      response.headers['Content-Length'] = @user.app.size.to_s
      send_file @user.app.path, filename: "meibaomosao.apk", content_type: "application/vnd.android.package-archive", x_sendfile: true
    end
  end

  require 'tempfile'
  require 'zip'
  def assets_bundle
    @user = User.find(params[:id])
    Zip.default_compression = Zlib::BEST_SPEED

    f = Tempfile.new
    Zip::File.open(f.path, Zip::File::CREATE) do |zipfile|
      @user.images.each_with_index do |image, index|
        if image.video_id.present?
          zipfile.add("#{index}.jpg", image.content.path)
          zipfile.add("#{index}.mp4", image.relate_video.content.path)
        end
      end
      zipfile.get_output_stream("targets.json") { |f| f.write @user.targets_json.to_json }
    end

    send_file f.path, filename: "#{@user.name}-image-pack.zip", type: "application/zip"
  end

  def videos
    @user = User.find(params[:id])
    @videos = @user.videos.order(id: :desc)
    render layout: false
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :gravatar,
                                 :telephone,
                                 :order_id)
  end

  # 为operator创建的新客户账号设定默认密码
  def set_password_for_client
    random_password = SecureRandom.hex(3)
    params[:user][:password] = random_password
    params[:user][:password_confirmation] = random_password
  end

  # 搜索用户
  def filter_users(users)
    s_text = params[:search]
    users = users.where("name like ? or order_id like ?", s_text+'%', s_text+'%') if s_text.present?
    if params[:app].present?
      if params[:app] == "on"
        users = users.where("app is not NULL")
      else
        users = users.where("app is NULL")
      end
    end
    users
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, klass="gravatar")
    #gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    gravatar_url = user.gravatar.thumb.url || "default_avatar.jpg"
    image_tag gravatar_url, alt: user.name, class: klass
  end

  def label_for(user)
    label_class =
        case user.role
        when "admin"
         "label-warning"
        when "operator"
          "label-info"
        else
          "label-success"
        end

    content_tag "span", user.role, class: "label #{label_class}"
  end
end

app/views/users/_gallery.html.erb
 <div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#images" aria-controls="images" role="tab" data-toggle="tab">
        <span class="glyphicon glyphicon-picture"></span> Photos
      </a>
    </li>

    <li role="presentation">
      <a href="#videos" aria-controls="videos" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-film"></span> Videos
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content mt-20">
    <div role="tabpanel" class="tab-pane fade in active" id="images">
      <div class="row">
        <% @user.images.each do |image| %>
          <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
              <%= image_tag image.thumb_url %>
            </a>
          </div>
        <% end %>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="videos">
      <div class="row">
        <% @user.videos.each do |video| %>
          <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
              <%= image_tag video.thumb_url %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_search_bar.html.erb
<%= content_for :header do %>
  <%= form_tag users_path, class: "navbar-form navbar-left", method: :get do %>
    <div class="form-group">
      <%= select_tag :app, options_for_select({"已上传APP": :on, "未上传APP": :off}, params[:app]), include_blank: true, class: "form-control header-search-input" %>
    </div>

    <div class="form-group">
      <%= text_field_tag :search, params[:search], class: "form-control header-search-input", placeholder: "姓名 订单号" %>
    </div>

    <%= hidden_field_tag "role", params[:role] %>

    <%= submit_tag "Search", class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>

<h1><%=@user.name%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render partial: 'shared/error_messages', locals: {obj: @user} %>

      <div class="form-group">
        <%= f.label "用户名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <!--div class="form-group">
        <%#= f.label "邮箱" %>
        <%#= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%#= f.label "电话" %>
        <%#= f.text_field :telephone, class: "form-control" %>
      </div-->

      <div class="form-group">
        <%= f.label "头像" %>
        <%= f.file_field :gravatar, class: "form-control" %>
      </div>

      <% if current_user.admin? %>
        <div class="form-group">
          <%= f.label "角色" %>
          <%= f.select :role, %w(admin operator client), {include_blank: true}, class: "form-control" %>
        </div>
      <%end%>

      <%= f.submit "更改信息", class: "btn btn-success form-control" %>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, 'reset password') %>

<h1>重置 <%=@user.name%> 的密码</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag reset_password_user_path(@user), method: :post do %>
      <%= render partial: 'shared/error_messages', locals: {obj: @user} %>

      <div class="form-group">
        <%= label_tag "旧的密码" %>
        <%= password_field_tag :old_password, nil, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag "密码" %>
        <%= password_field_tag :password, nil, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag "重复密码" %>
        <%= password_field_tag :password_confirmation, nil, class: "form-control" %>
      </div>

      <%= submit_tag "更改信息", class: "btn btn-success form-control" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render partial: "search_bar" %>

<div class="row mt-20">

  <div class="col-lg-12 col-md-12 col-sm-12">
    <%= link_to new_user_path(build_client: true), class: 'btn btn-success pull-right' do %>
      <span class="glyphicon glyphicon-plus-sign"></span> 添加新客户
    <% end %>
  </div>

  <div class="col-md-12">
    <table class="table table-responsive table-condensed table-hover table-strip table-content-middle">
      <thead>
      <tr>
        <th>#</th>
        <th>头像</th>
        <th>姓名</th>
        <th>密码</th>
        <th>订单号</th>
        <th>照片数</th>
        <th>视频数</th>
        <th>APP</th>
        <%if current_user.admin? %><th>角色</th><%end%>
        <th>操作</th>
      </tr>
      </thead>

      <tbody>
      <%@users.each_with_index do |user, index|%>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to gravatar_for(user), user_path(user) %></td>
          <td><%= user.name %></td>
          <td><%= user.password_text %></td>
          <td><%= user.order_id %></td>
          <td><%= user.images.count %></td>
          <td><%= user.videos.count %></td>
          <td><%= "<span class='glyphicon glyphicon-phone'></span>".html_safe if user.app.present? %></td>
          <%if current_user.admin? %><th><%= label_for user %></th><%end%>
          <td>
            <%= link_to user_attachments_path(user),
                        class: "btn btn-default btn-sm",
                        title: "上传",
                        data: {toggle: "tooltip", placement: "top"} do %>
              <span class="glyphicon glyphicon-upload"></span>
            <% end %>
          </td>
        </tr>
      <%end%>
      </tbody>
    </table>

    <div class="text-center">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if params[:build_client].present? %>
  <% provide(:title, '创建客户账号') %>
  <h1>创建客户账号</h1>
<% else %>
  <% provide(:title, '注册用户') %>
  <h1>注册</h1>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render partial: 'shared/error_messages', locals: {obj: @user} %>

      <div class="form-group">
      <%= f.label "用户名" %>
      <%= f.text_field :name, class: "form-control" %>
      </div>

      <% if params[:build_client].present? %>
      <div class="form-group">
        <%= f.label "用户订单号" %>
        <%= f.text_field :order_id, class: "form-control" %>
      </div>
      <% end %>

      <!--div class="form-group">
        <%#= f.label "手机号码" %>
        <%#= f.text_field :telephone, class: "form-control" %>
      </div>

      <div class="form-group">
        <%#= f.label "邮箱" %>
        <%#= f.text_field :email, class: "form-control" %>
      </div-->

      <% if params[:build_client].present? %>
        <%= hidden_field_tag "build_client", true%>
      <% else %>
        <div class="form-group">
          <%= f.label "密码" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label "确认密码" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      <%end%>

      <%= f.submit "提交", class: "btn btn-success form-control" %>
     <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<div class="pull-right mt-20">
  <% if can? :visit_assets, @user%>
    <%= link_to user_attachments_path(@user),
                class: "btn btn-default btn-sm",
                title: "上传照片和视频",
                data: {toggle: "tooltip", placement: "top"} do %>
      <span class="glyphicon glyphicon-upload"></span>
    <% end %>
  <% end %>

  <% if can? :download_assets_bundle, @user%>
    <%= link_to assets_bundle_user_path(@user),
                class: "btn btn-default btn-sm",
                title: "下载照片和视频",
                data: {toggle: "tooltip", placement: "top"} do %>
      <span class="glyphicon glyphicon-download-alt"></span>
    <% end %>
  <% end %>

  <% if can? :update, @user%>
    <%= link_to edit_user_path(@user),
                class: "btn btn-default btn-sm",
                title: "编辑用户信息",
                data: {toggle: "tooltip", placement: "top"} do %>
      <span class="glyphicon glyphicon-edit"></span>
    <% end %>

    <%= link_to reset_password_user_path(@user),
                class: "btn btn-default btn-sm",
                title: "重置此用户密码",
                data: {toggle: "tooltip", placement: "top"} do %>
      <span class="glyphicon glyphicon-lock"></span>
    <% end %>
  <% end %>

  <% if can? :delete, @user%>
    <%= link_to user_path(@user),
                method: :delete,
                data: {confirm: "确认删除用户所有数据？", toggle: "tooltip", placement: "top"},
                title: "删除此用户",
                class: "btn btn-default bg-danger btn-sm" do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12  mt-20">
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-user"></span> 用户信息
      </div>

      <table class="table">
        <tr>
          <td rowspan="<%= can?(:upload_app, current_user) ? 4:3 %>" style="width: 20%;">
            <h1 class="text-center">
              <%= gravatar_for @user, "garavatar gravatar-lg" %>
            </h1>
            <h3 class="text-center"><%= @user.name %></h3>
          </td>
          <th style="width: 15%;"><span class="glyphicon glyphicon-user"></span> 角色</th>
          <td style="width: 65%;"><%= label_for @user %></td>
        </tr>
        <tr>
          <th><span class="glyphicon glyphicon-file"></span> 订单号</th>
          <td><%= @user.order_id%></td>
        </tr>
        <tr>
          <th><span class="glyphicon glyphicon-apple"></span> 魔扫应用</th>
          <td>
            <% if @user.app.blank? %>
              ---
            <% else %>
              <%= link_to @user.app.file.filename, @user.app.url %>
            <% end %>
          </td>
        </tr>
        <% if can? :upload_app, current_user %>
          <tr>
            <td colspan="2">
              <div id="fileuploader"></div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-lg-12">
    <%= render partial: "gallery" %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(function(){
        // 上传app
        $("#fileuploader").uploadFile({
            url: "<%=app_user_path(@user)%>",
            fileName: "app",
            headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
            statusBarWidth: "100%",
            dragdropWidth: "100%",
            dragDropStr: "<span><b>拖拽文件到此出上传</b></span>",
            uploadButtonClass: "btn btn-success btn-sm",
            uploadStr: "上传",
            allowedTypes: "apk",
            extErrorStr: "不支持此格式文件上传. 支持的文件格式为: ",
            maxFileSize: 100 * 1024 * 1024, //10M
            sizeErrorStr: "文件过大，上传文件最大: ",
            maxFileCount: 1,
        });
    });
</script>

app/views/users/videos.html.erb
<%= render partial: "/attachments/preview_list", locals: {attachments: @videos}%>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
      // 更新照片关联的视频
      $("a.video-select").on("click", function (e) {
          var $link = $(this);
          var url = $(this).data("url");
          var jqxhr = $.post(url, function (resp) {
              $link.parent().parent().parent().children(".btn").html(resp['video_title'] + '<span class="caret"></span>');
              toastr.success(resp["message"]);
          })
              .fail(function (resp) {
                  toastr.error(resp["message"] || "更新失败");
              });

          var image_id = "<%=params[:image_id]%>";
          $(".select-video-btn" + "." + image_id).text($link.data("title"));
          $("#video-list-dialog").modal('toggle');
      });
  })
</script>