config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get 'sessions/new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete "logout" => "sessions#destroy"


  resources :users, constraints: { id: /\d+/ } do
    member do
      get :reset_password, action: "edit_password"
      post :reset_password, action: "update_password"
      post :app, action: "upload_app"
      get :app, action: "download_app"
      get :assets_bundle
      get :videos
    end

    resources :attachments, constraints: { id: /\d+/ } do
      member do
        post "relate_video/:video_id", action: "relate_video", as: "relate_video_attachment"
      end
    end
  end

  resources :clients, constraints: { id: /\d+/ }

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :users, only: [:index, :create, :show, :update, :destroy] do
        member do
          get :images
          get :ar_images
        end
      end
      # 原文有 microposts, 我们现在把它注释掉
      # resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :content, ::AttachmentUploader
  serialize :meta_info, Hash
  belongs_to :user
  #belongs_to :create_by, class_name: "User", foreign_key: "create_by"

  before_save :extract_meta_info
  before_save :set_content_type
  after_save :generate_video_thumb
  after_destroy :delete_thumb


  def creator
    User.find(creator_id)
  end

  def generate_video_thumb
    movie = FFMPEG::Movie.new(self.content.path)
    movie.screenshot(video_thumb_path, seek_time: 3, resolution: "320x240")
  end

  def extract_meta_info
    case content.content_type
    when /.*jpeg/
      image = MiniMagick::Image.open(self.content.path)
      self.meta_info = {
          height: image.height,
          width: image.width,
          size: image.size,
      }
    when /.*mp4/
      movie = FFMPEG::Movie.new(self.content.path)
      self.meta_info = {
          height: movie.height,
          width: movie.width,
          duration: movie.duration,
          size: movie.size
      }
    else
      self.meta_info = {}
    end
  end

  def set_content_type
    case self.content.content_type
    when /.*jpeg/i
      self.content_type = "jpeg"
    when /.*mp4/i
      self.content_type = "mp4"
    else
      self.content_type = self.content.content_type
    end
  end

  def image?
    content_type == "jpeg"
  end

  def video?
    content_type == "mp4"
  end

  def meta_info_str
    str = "#{self.meta_info[:width]}x#{self.meta_info[:height]} #{(self.meta_info[:size].to_f / 1024 / 1024).round(2)}M"
    str += " #{self.meta_info[:duration].to_i}s" if self.video?
    str
  end

  def thumb_url
    if image?
      content.thumb.url
    elsif video?
      video_thumb_url
    else
      "/default_video_thumb.jpg"
    end
  end

  def thumb_path
    if self.video?
      video_thumb_path
    else
      self.content.thumb.path
    end
  end

  def video_thumb_path
    video_path = content.path
    File.join(File.dirname(video_path), File.basename(video_path).split('.').first + ".jpg")
  end

  def video_thumb_url
    video_url = content.url
    File.join(File.dirname(video_url), File.basename(video_url).split('.').first + ".jpg")
  end

  def delete_thumb
    FileUtils.rm(thumb_path) if File.exist?(thumb_path)
  end

  def relate_video
    self.class.where(id: video_id).first
  end

  def has_video?
    self.video_id.present? && self.class.find_by_id(self.video_id).present?
  end

  def video
    Attachment.find(self.video_id) if has_video?
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def new
  end

  def create
    @user = User.find(params[:user_id])
    @attachment = @user.attachments.build(content: params[:content], creator_id: current_user.id)

    if @attachment.save
      render json: @attachment.to_json, status: 200
    else
      render json: @attachment.errors, status: 300
    end
  end

  def show
    @attachment = Attachment.find(params[:id])

    render layout: false
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:user_id])
    @attachment = Attachment.find(params[:id])
    if @attachment.destroy
      flash['success'] = "#{@attachment.content.file.filename} 删除成功"
    else
      flash['error'] = "#{@attachment.content.file.filename} 删除失败"
    end

    redirect_to user_attachments_path(@user)
  end

  def relate_video
    image = Attachment.find(params["id"])
    video = Attachment.find(params["video_id"])

    if image.blank? || video.blank?
      render json: {status: 404, message: "没有找到数据，更新失败"}
    else
      image.video_id = video.id
      if image.save
        render json: {status: 200,
                      message: "关联#{video.content.file.filename}到#{image.content.file.filename}成功",
                      video_title: video.content.file.filename}
      else
        render json: {status: 500, message: "保存数据失败"}
      end
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_preview_list.html.erb
<ul class="photo-list">
  <% attachments.each_with_index do |attachment, index| %>
    <li>
      <a href="javascript:void(0);"
         data-title="<%= attachment.content.file.filename %>"
         data-url="<%= user_attachment_path(@user, attachment) %>"
         data-order="<%= index %>"
         class="attachment-thumbnail">
        <%= image_tag attachment.thumb_url, height: 150, alt: attachment.content.filename, class: "img-thumbnail" %>
      </a>

      <div class="info">
        <h4 class="text-left">#<%= index + 1 %> <%= attachment.content.file.filename %></h4>
        <ul class="info-list">
          <li>
            <span class="glyphicon glyphicon-user"></span>
            <%= attachment.creator&.name %>
          </li>
          <li>
            <span class="glyphicon glyphicon-time"></span>
            <%= attachment.created_at.to_s(:db) %>
          </li>
          <li>
            <span class="glyphicon glyphicon-info-sign"></span>
            <%= "#{attachment.meta_info_str}" %>
          </li>

          <% if attachment.image? %>
          <li>
            <span class="glyphicon glyphicon-facetime-video"></span>
            <a href="javascript:void(0);"
               data-user-id="<%= @user.id %>"
               data-image-id="<%= attachment.id %>"
               data-url="<%= videos_user_path(@user, {image_id: attachment.id}) %>"
               class="select-video-btn <%=attachment.id%>">
              <%= attachment.relate_video.blank? ? "----" : attachment.relate_video.content.file.filename %>
            </a>
          </li>
          <% end %>

          <%if params[:image_id].present?%>
          <li>
            <a href="javascript:void(0);"
                 class="btn btn-success btn-sm video-select"
                 data-title="<%=attachment.content.file.filename%>"
                 data-url="<%=relate_video_attachment_user_attachment_path(@user, params[:image_id], attachment.id)%>">
              选择
            </a>
          </li>
          <% end %>
        </ul>
      </div>

      <div class="operation">
        <%= link_to attachment.content.url,
                    class: "btn btn-success btn-sm" do %>
          <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        <% end %>

        <%= link_to user_attachment_path(@user, attachment),
                    method: :delete,
                    data: {confirm: '确定删除?'},
                    class: "btn btn-danger btn-sm" do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/attachments/create.html.erb
<h1>Attachments#create</h1>
<p>Find me in app/views/attachments/create.html.erb</p>

app/views/attachments/destroy.html.erb
<h1>Attachments#destroy</h1>
<p>Find me in app/views/attachments/destroy.html.erb</p>

app/views/attachments/edit.html.erb
<h1>Attachments#edit</h1>
<p>Find me in app/views/attachments/edit.html.erb</p>

app/views/attachments/index.html.erb
<% provide :title, @user.name %>

<div class="row mt-20">
  <div class="col-md-4" >
    <div class="uploader">
      <div id="fileuploader"></div>
    </div>
  </div>

  <div class="col-md-8">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#images" aria-controls="images" role="tab" data-toggle="tab">
          <span class="glyphicon glyphicon-picture"></span> Photos
        </a>
      </li>

      <li role="presentation">
        <a href="#videos" aria-controls="videos" role="tab" data-toggle="tab">
          <span class="glyphicon glyphicon-film"></span> Videos
        </a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="images">
        <%= render partial: "preview_list", locals: {attachments: @user.images.order(id: :desc)}%>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="videos">
        <%= render partial: "preview_list", locals: {attachments: @user.videos.order(id: :desc)}%>
      </div>
    </div>
  </div>
</div>


<div id="attachment-dialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>loading....</p>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="video-list-dialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Video List</h4>
      </div>
      <div class="modal-body" style="height: 700px; overflow: scroll;">
        <p>loading....</p>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(function(){
        // 上传附件
        $("#fileuploader").uploadFile({
            url: "<%=user_attachments_path(@user)%>",
            fileName: "content",
            headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
            statusBarWidth: "100%",
            dragdropWidth: "100%",
            dragDropStr: "<span><b>拖拽文件到此出上传</b></span>",
            uploadButtonClass: "btn btn-success btn-sm",
            uploadStr: "上传",
            allowedTypes: "jpg,jpeg,mp4",
            extErrorStr: "不支持此格式文件上传. 支持的文件格式为: ",
            maxFileSize: 10 * 1024 * 1024, //10M
            sizeErrorStr: "文件过大，上传文件最大: ",
        });
    });
</script>

app/views/attachments/new.html.erb
<h1>Attachments#new</h1>
<p>Find me in app/views/attachments/new.html.erb</p>

app/views/attachments/show.html.erb
<%if @attachment.content_type == "jpeg"%>
  <%= image_tag @attachment.content.url, width: "100%"%>
<%else%>
  <video width="100%" id="vdHotPress" autoplay controls>
    <!-- set width to 100% and add controls for play and volume buttons-->
    <source src="<%=@attachment.content.url%>" type="video/mp4"/>
    Your browser does not support the video tag.
  </video>
<%end%>

app/views/attachments/update.html.erb
<h1>Attachments#update</h1>
<p>Find me in app/views/attachments/update.html.erb</p>