config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get 'sessions/new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete "logout" => "sessions#destroy"


  resources :users, constraints: { id: /\d+/ } do
    member do
      get :reset_password, action: "edit_password"
      post :reset_password, action: "update_password"
      post :app, action: "upload_app"
      get :app, action: "download_app"
      get :assets_bundle
      get :videos
    end

    resources :attachments, constraints: { id: /\d+/ } do
      member do
        post "relate_video/:video_id", action: "relate_video", as: "relate_video_attachment"
      end
    end
  end

  resources :clients, constraints: { id: /\d+/ }

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :users, only: [:index, :create, :show, :update, :destroy] do
        member do
          get :images
          get :ar_images
        end
      end
      # 原文有 microposts, 我们现在把它注释掉
      # resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2018-2019 copyright by XXX INC.
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于我们", about_path %></li>
      <li><%= link_to "联系我们", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#moosao-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag "brand.jpg" %>
      </a>

      <%#= link_to "MooSao", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="moosao-navbar-collapse" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%='active' if current_page?(controller: 'static_pages', action: 'home')%>"><%= link_to "首页", root_path %></li>

        <% if can? :read, User %>
          <li class="<%= 'active' if controller.class == UsersController %>"><%= link_to "用户管理", users_path %></li>
        <% end %>
      </ul>

      <%=yield :header%>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= gravatar_for(current_user, "gravatar-sm")%>
              <%=current_user.name%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "<span class='glyphicon glyphicon-user'></span> 我的信息".html_safe, user_path(current_user) %></li>
              <li><%= link_to "<span class='glyphicon glyphicon-edit'></span> 更新信息".html_safe, edit_user_path(current_user) %></li>
              <li><%= link_to "<span class='glyphicon glyphicon-credit-card'></span> 修改密码".html_safe, reset_password_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "<span class='glyphicon glyphicon-log-out'></span> 退出".html_safe, logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "登录", login_path %></li>
          <li><%= link_to "注册", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>

    <%if current_page?(controller: "static_pages", action: "home")%>
      <%= yield :home%>
    <%else%>
      <div class="main container">
        <%= yield %>

        <div class="footer">
          <%= render "layouts/footer" %>
          <%= debug params if Rails.env.development? %>
          <%= debug flash if Rails.env.development? %>
        </div>
      </div>
    <% end %>
  </body>

  <script type="text/javascript" charset="utf-8">
    $(function(){
        <% flash.each do |message_type, message| %>
        toastr["<%=message_type%>"]("<%=message%>", {timeOut: 5000});
        <% end %>
    })
  </script>
</html>